### ISSUE TITLE
AcmAutoRefreshSelect error when window is not set

### ISSUE THREAD

**Issue by birsanv** [open-cluster-management/ui-components#188]
I am trying to use the AcmAutoRefreshSelect on the common page header
using @open-cluster-management/ui-components": "^0.1.184

I want to change the current implementation, and make use of the AcmPageHeader
So I want to change this line
https://github.com/open-cluster-management/application-ui/blob/master/src-web/containers/App.js#L126

and replace with 
```
      <div className="expand-vertically">
        <AcmPageHeader {...headerArgs} />
        <Switch>
          <Route
...
```

```
    const headerArgs = {
      title: 'Applications',
      titleTooltip: 'Doc link',
      controls: (
        <AcmAutoRefreshSelect
          refetch={refetch}
          refreshIntervals={[15, 30, 60, 5 * 60, 30 * 60, 0]}
        />
      )
    }

const refetch = () => {
...
}
```

The window object is not set initially and I get this exception on the AcmAutoRefreshSelect

ReferenceError: window is not defined
    at /Users/vbirsan/Documents/data/git/master/application-ui/node_modules/@open-cluster-management/ui-components/src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx:61:16
    at useReducer (/Users/vbirsan/Documents/data/git/master/application-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:1194:57)

https://github.com/open-cluster-management/ui-components/blob/master/src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx#L61 

<img width="935" alt="Screen Shot 2021-02-01 at 5 26 27 PM" src="https://user-images.githubusercontent.com/43010150/106527498-5dc54680-64b5-11eb-9485-778dcef5b519.png">

**Comment by birsanv** [comment]
@RobDolares I am tagging you since you seem to be the initial creator ..is it possible I am not using the component the way is intended to ?
fyi @chenz4027

**Comment by jlpadilla** [comment]
@birsanv Are you doing server-side rendering?

**Comment by KevinFCormier** [comment]
@jlpadilla I believe there is an old server-side rendering setup in our code that isn't really effective and should probably just be removed.

**Comment by birsanv** [comment]
@KevinFCormier thanks then I'll hold off to the app ui refresh action change until we move the header rendering 
We can close this issue unless we want to update the code that validates the window existence

This line seems to verify if the window exists
https://github.com/open-cluster-management/ui-components/blob/master/src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx#L61
>>  } else if (window && window.localStorage && window.localStorage.getItem(key)) {

but the code is going to fail here if no window
https://github.com/open-cluster-management/ui-components/blob/master/src/AcmAutoRefreshSelect/AcmAutoRefreshSelect.tsx#L66
>> window.localStorage.setItem(key, `${DEFAULT_REFRESH_TIME * 1000}`)

**Comment by birsanv** [comment]
closing, the refresh action is updated on a separate task https://github.com/open-cluster-management/backlog/issues/10776
